# Generated by Django 5.1.3 on 2024-11-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productosapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productos',
            new_name='products',
        ),
    ]
